# Generated by Django 5.2 on 2025-04-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
