# Generated by Django 5.2 on 2025-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='move_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
