# Generated by Django 5.2 on 2025-04-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_wishlist_move_to_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
