# Generated by Django 5.2 on 2025-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
