# Generated by Django 5.2 on 2025-05-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='cart_id',
        ),
    ]
